server:
  port: 9191
  servlet:
     context-path: /ddm/api/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_ddm?createDatabaseIfNotExist=true
    username: root
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:           
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
  jackson:
    serialization:
       fail-on-empty-beans: false 

  application:
    name: ddm-auth-service


## logging:level:    org:      hibernate:        type: trace
        

check-user-scopes: false
        
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin
        